using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using Windows.Win32;
using Windows.Win32.Foundation;

namespace VkDiag.Interop;

/// <summary>
/// Статичний клас для низькорівневої взаємодії з Windows Package Manager API.
/// </summary>
/// <remarks>
/// Цей клас використовує P/Invoke виклики (згенеровані CsWin32) для доступу до функцій <c>appmodel.h</c> та <c>shlwapi.h</c>.
/// Він дозволяє отримувати інформацію про встановлені Appx/MSIX пакети, їх версії та локалізовані назви.
/// <para>
/// <b>Увага:</b> Клас використовує <c>unsafe</c> код для роботи з вказівниками та буферами пам'яті.
/// </para>
/// </remarks>
public static unsafe class PackageManager
{
    // this is a wrapper over generated p/invoke crust generated by https://github.com/microsoft/CsWin32
  
    /// <summary>
    /// Знаходить повні імена пакетів (Package Full Names) для заданого сімейства пакетів.
    /// </summary>
    /// <param name="packageFamily">
    /// Ім'я сімейства пакетів (Package Family Name), наприклад <c>Microsoft.D3DMappingLayers_8wekyb3d8bbwe</c>.
    /// </param>
    /// <returns>
    /// Список рядків, що містять повні імена знайдених пакетів.
    /// Повертає порожній список, якщо пакети не знайдено.
    /// </returns>
    /// <exception cref="Win32Exception">
    /// Викидається, якщо Win32 API повертає помилку (крім <c>ERROR_INSUFFICIENT_BUFFER</c> при першому виклику).
    /// </exception>
    /// <remarks>
    /// Метод викликає <see cref="PInvoke.FindPackagesByPackageFamily"/> двічі:
    /// <list type="number">
    /// <item>Перший раз: щоб отримати кількість пакетів (<c>count</c>) та необхідний розмір буфера (<c>bufferLength</c>).</item>
    /// <item>Другий раз: щоб заповнити виділені буфери реальними даними.</item>
    /// </list>
    /// </remarks>
    public static List<string> FindPackagesByPackageFamily(string packageFamily)
    {
        uint count = 0, bufferLength = 0;
        var result = PInvoke.FindPackagesByPackageFamily(
            packageFamily,
            PInvoke.PACKAGE_FILTER_HEAD,
            ref count,
            default,
            ref bufferLength,
            default,
            default
        );
        if (result is not WIN32_ERROR.ERROR_INSUFFICIENT_BUFFER and not WIN32_ERROR.NO_ERROR)
            throw new Win32Exception((int)result, "Failed to query package list");
        
        if (count is 0)
            return [];
        
        var pkgFullNameList = new PWSTR[count];
        Span<char> charBuf = new char[bufferLength];
        Span<uint> props = new uint[count];
        result = PInvoke.FindPackagesByPackageFamily(
            packageFamily,
            PInvoke.PACKAGE_FILTER_HEAD,
            ref count,
            pkgFullNameList,
            ref bufferLength,
            charBuf,
            props
        );
        if (result is not WIN32_ERROR.NO_ERROR)
            throw new Win32Exception((int)result, "Failed to retrieve package names");
        
        return pkgFullNameList.Select(n => n.ToString()).ToList();
    }

    /// <summary>
    /// Отримує версію встановленого пакета.
    /// </summary>
    /// <param name="packageFullName">Повне ім'я пакета (Package Full Name).</param>
    /// <param name="defaultVersion">Значення, що повертається у разі помилки або неможливості отримати версію.</param>
    /// <returns>
    /// Рядок у форматі <c>" v{Major}.{Minor}.{Build}.{Revision}"</c> або <paramref name="defaultVersion"/>.
    /// </returns>
    /// <remarks>
    /// Метод використовує <see cref="PInvoke.OpenPackageInfoByFullName"/> та <see cref="PInvoke.GetPackageInfo"/> 
    /// для отримання структури <c>PACKAGE_INFO</c>. Далі відбувається ручний розбір бінарного буфера для вилучення 
    /// полів версії з <c>PACKAGE_VERSION</c> struct.
    /// </remarks>
    public static string GetPackageVersion(string packageFullName, string defaultVersion)
    {
        if (PInvoke.OpenPackageInfoByFullName(packageFullName, out var pkgRef) is not WIN32_ERROR.NO_ERROR)
            return defaultVersion;
        
        try
        {
            uint bufLen = 0;
            var result = PInvoke.GetPackageInfo(
                pkgRef,
                PInvoke.PACKAGE_INFORMATION_BASIC,
                &bufLen
            );
            if (result is not WIN32_ERROR.ERROR_INSUFFICIENT_BUFFER)
                return defaultVersion;

            var buf = new byte[bufLen];
            uint count = 0;
            fixed (byte* pBuf = buf)
            {
                result = PInvoke.GetPackageInfo(
                    pkgRef,
                    PInvoke.PACKAGE_INFORMATION_BASIC,
                    &bufLen,
                    pBuf,
                    &count
                );
            }
            if (result is not WIN32_ERROR.NO_ERROR)
                return defaultVersion;

            // PACKAGE_INFO https://learn.microsoft.com/en-us/windows/win32/api/appmodel/ns-appmodel-package_info
            var pkgIdOffset = 4 + 4 + IntPtr.Size * 3;
            var revision = BitConverter.ToUInt16(buf, pkgIdOffset + 8);
            var build = BitConverter.ToUInt16(buf, pkgIdOffset + 10);
            var minor = BitConverter.ToUInt16(buf, pkgIdOffset + 12);
            var major = BitConverter.ToUInt16(buf, pkgIdOffset + 14);
            return $" v{major}.{minor}.{build}.{revision}";
        }
        finally
        {
            PInvoke.ClosePackageInfo(pkgRef);
        }
    }

    /// <summary>
    /// Отримує локалізовану назву додатка з його ресурсів (App Store Name).
    /// </summary>
    /// <param name="packageFullName">Повне ім'я пакета.</param>
    /// <param name="defaultName">Значення за замовчуванням, якщо ресурс не знайдено.</param>
    /// <returns>Локалізована назва програми або <paramref name="defaultName"/>.</returns>
    /// <remarks>
    /// Використовує функцію <see cref="PInvoke.SHLoadIndirectString"/> для завантаження рядка ресурсу за URI схемою:
    /// <c>@{PackageFullName?ms-resource://ResourceName}</c>.
    /// <br/>
    /// У даному випадку жорстко закодовано ресурс <c>ms-resource://Microsoft.D3DMappingLayers/Resources/AppStoreName</c>,
    /// що є специфічним для пакетів сумісності OpenCL/OpenGL.
    /// </remarks>
    public static string GetAppStoreName(string packageFullName, string defaultName)
    {
        Span<char> staticBuf = stackalloc char[512];
        var source = $"@{{{packageFullName}?ms-resource://Microsoft.D3DMappingLayers/Resources/AppStoreName}}";
        fixed (char* pBuf = staticBuf)
        fixed (char* pSource = source)
        {
            var output = new PWSTR(pBuf);
            if (PInvoke.SHLoadIndirectString(new(pSource), output, (uint)staticBuf.Length).Succeeded)
                return output.ToString();
        }
        return defaultName;
    }
}